### ISSUE TITLE
Node-red crash, when I send any commands

### ISSUE THREAD

**Issue by bega1986** [inwaar/node-red-contrib-gree-hvac#12]
I see all of the information from my AC, but when I send a command, then node-red is crashing. The AC execute the command, but the node-red is shutting down with the folloving errors:

14 Nov 11:24:05 - [red] Uncaught Exception:
14 Nov 11:24:05 - [error] TypeError: Cannot read properties of undefined (reading '0')
at /data/data/com.termux/files/home/.node-red/node_modules/gree-hvac-client/lib/client.js:383:46
at Array.forEach (<anonymous>)
at Client._handleUpdateConfirmResponse (/data/data/com.termux/files/home/.node-red/node_modules/gree-hvac-client/lib/client.js:382:18)
at Client._handleResponse (/data/data/com.termux/files/home/.node-red/node_modules/gree-hvac-client/lib/client.js:312:29)                             at Socket.<anonymous> (/data/data/com.termux/files/home/.node-red/node_modules/gree-hvac-client/lib/client.js:113:52)
at Socket.emit (node:events:513:28)
at UDP.onMessage [as onmessage] (node:dgram:930:8)

My HVAC type:
Gree | G-TECH GWH12AEC

**Comment by bega1986** [comment]
?

**Comment by sixtybi** [comment]
I have the same problem. Have you found a solution for this?
I have two types of AC in my home:
Syen SOH09BO-E32DA4A2 (this has the same issue as descibed above)
Syen SOH12MU-E32DA1D (this is working fine with this node)

**Comment by sixtybi** [comment]
I have described a WA for this in Issue 11.
I would suggest to merge these two issues as these two are the same.

**Comment by bega1986** [comment]
I haven't found a solution yet :(

**Comment by sixtybi** [comment]
Try my workaround. It works, but not the best solution, as you have to wait
for the values to be updated in the UI

**Comment by apachler** [comment]
This no longer crashes Node-RED in the maintained fork: **[apachler/node-red-contrib-gree-hvac](https://github.com/apachler/node-red-contrib-gree-hvac)** (release [v1.5.0](https://github.com/apachler/node-red-contrib-gree-hvac/releases/tag/v1.5.0)).

The malformed-response path that threw `TypeError: Cannot read properties of undefined (reading '0')` in `_handleUpdateConfirmResponse` is now caught at two layers:

1. the forked `gree-hvac-client` (v3.0.0) wraps response handling in an async `.catch` that turns the throw into an `'error'` event instead of an uncaught exception, and
2. the new `ConnectionManager` absorbs that event as a non-fatal `'failure'` and reconnects, instead of letting the process die.

A `validateProperties` step also drops unknown / out-of-enum keys before sending, which shrinks the surface that provokes odd device responses in the first place.

Honest caveat: the underlying parse weakness still exists, so a device that genuinely returns malformed `res` packets will cause a reconnect blip rather than crash. If you can still reproduce that on your G-TECH GWH12AEC, a `logLevel: "debug"` capture of the raw `res` packet would help us harden the parser itself.

> Note: npm still serves the original `0.3.0`; grab the fork's GitHub Release tarball.

**Comment by apachler** [comment]
Follow-up: beyond the v1.5.0 error-absorption (which already stopped the process from dying), the fork's [v1.5.1](https://github.com/apachler/node-red-contrib-gree-hvac/releases/tag/v1.5.1) now hardens the parser **at the source** (`gree-hvac-client` v3.0.2).

`_handleUpdateConfirmResponse` and `_handleStatusResponse` validate that the parallel `opt`/`val`/`p` and `cols`/`dat` arrays are actually present and well-formed (and skip index overruns), then **skip a malformed packet with a warning instead of throwing**. That's the exact `Cannot read properties of undefined (reading '0')` path from this issue — so a device that occasionally returns an odd `res`/`dat` packet no longer even causes a reconnect blip, let alone a crash. Covered by a regression test suite for the malformed-packet paths.

> Note: npm still serves the original `0.3.0`; grab the fork's GitHub Release tarball.
