### ISSUE TITLE
Example FLow crashing with uncaught Exception

### ISSUE THREAD

**Issue by vellad1** [inwaar/node-red-contrib-gree-hvac#5]
Hi,

I just installed the node, imported the example node and configured the IP of the Gree A/C I have.

I go to the dashboard and when i click on the Power button node-red itself craps out with an uncaught exception.

> 15 Feb 16:56:25 - [red] Uncaught Exception:
15 Feb 16:56:25 - TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:278:15)
    at Decipheriv.update (node:internal/crypto/cipher:179:11)
    at EncryptionService.decrypt (/root/.node-red/node_modules/gree-hvac-client/lib/encryption-service.js:42:30)
    at Client._handleResponse (/root/.node-red/node_modules/gree-hvac-client/lib/client.js:291:46)
    at Socket.<anonymous> (/root/.node-red/node_modules/gree-hvac-client/lib/client.js:113:52)
    at Socket.emit (node:events:376:20)
    at UDP.onMessage [as onmessage] (node:dgram:925:8)
root@ubuntu-lts:~#

Any ideas what I can do? Thanks.

**Comment by inwaar** [comment]
HI, what are the versions of NodeJS and NodeRed?
